### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by JunMa11** [xuuuuuuchen/Active-Contour-Loss#1]
Hi @xuuuuuuchen ,

I really enjoy your paper on active contour loss.
When the code will be released?

Best,
Jun

**Comment by xuuuuuuchen** [comment]
Dear Jun,

The code is released now.

Best regards,
Xu

**Comment by JunMa11** [comment]
Hi @xuuuuuuchen ,
Thank you very much.
I will try it.
