### ISSUE TITLE
why the length is component of the loss?

### ISSUE THREAD

**Issue by step404** [xuuuuuuchen/Active-Contour-Loss#11]
Hi, I have some questions about the length.
T(length) is the length of target;P(length) is the length of prediction.
And the |P-T| is the component of the loss.
All Right?

**Comment by Luoxd1996** [comment]
No, your understanding is wrong, maybe you need to read the paper "Active Contours Without Edges", the length term is just used for regularization. Now, we extend the idea and implement it in [ACELoss](https://github.com/HiLab-git/ACELoss), maybe you can read and use it for more details.

**Comment by step404** [comment]
Thanks.
