### ISSUE TITLE
What's the input shape in AC loss?

### ISSUE THREAD

**Issue by JunMa11** [xuuuuuuchen/Active-Contour-Loss#2]
Hi @xuuuuuuchen ,

Thanks for sharing the code very much.
1) What's the input shape in AC loss?
Intuitively, the input shape is:
`y_true.shape = (batch_size, class num, img_x, img_y) = y_pred.shape`.
For ACDC dataset, the shape is (batch_size, 4, 256,256). 

However, in the discussion part, the paper said, "the proposed loss function can also be extended to solve multi-phase segmentation problems". Thus, it means the paper uses AC loss in a binary version, right?

2) A technique question: what's the purpose for following code?
https://github.com/xuuuuuuchen/Active-Contour-Loss/blob/f90dd4a4cc4dc8a8c4f0090b2c41a03d7d5f55d3/Active-Contour-Loss.py#L17-L18

Best,
Jun

**Comment by xuuuuuuchen** [comment]
Hi Jun,

The shape of input tensor is “channel-first”.

We treated the input images as grayscale images (1 channel).

Our method is only able to work on a 2-class segmentation.

For the question 2, please refer the equation 11 in the paper.

Best,
Xu

**Comment by JunMa11** [comment]
Hi @xuuuuuuchen ,

Thanks for your quick reply.

In eq. (11), length term requires to compute the derivative of `u`. However, the derivative has been computed by forward difference here.

https://github.com/xuuuuuuchen/Active-Contour-Loss/blob/f90dd4a4cc4dc8a8c4f0090b2c41a03d7d5f55d3/Active-Contour-Loss.py#L14-L15

**Comment by xuuuuuuchen** [comment]
The purpose for line 17 & 18 line is to compute within (a-1, a-1) shape, because after line 14 & 15, the shape of x & y are like (a-1, a) and (a, a-1),

Hope it answers your question.

**Comment by JunMa11** [comment]
Hi @xuuuuuuchen ,
Thanks for your reply.
I understand, but I think the shape of `delta_x/y` is (a-2, a-2) in your code. For ACDC, it is (254, 254).

**Comment by xuuuuuuchen** [comment]
@JunMa11 Yes, it is (a-2, a-2) not (a-1, a-1) in this code. I'm trying to make sure the shape of `delta_x/delta_y ` is always square as well as contain meaningful info., but you could try on (a-1, a-1). I think there's no big difference if the image size is large enough.

Hope it answers your question.

**Comment by JunMa11** [comment]
Got it. Yes, `a-1` or `a-2` is not critical.
Thanks for your reply very much.
